### ISSUE TITLE
"Transaction" sort label has no background in main view, unlike other labels

### ISSUE THREAD

**Issue by xofe** [afterxleep/Bouncer#14]
Just trying out this app - I have a feeling it'll come in very handy!

One little thing I noticed while playing with it is that the "transaction" sort label seems to have no background colour in the main list view, making it hard to read.

![missing background on "transaction" label](https://user-images.githubusercontent.com/22776566/132122422-2f384732-7c0b-4867-a597-c98881500ffd.png)

This occurs on an iPhone SE 1st gen running iOS 14.7.1, with version 2.1.0 of Bouncer from the App Store.

**Comment by afterxleep** [comment]
Hey!,  Thanks for reporting.   

This has been fixed in v2.1.1

**Comment by zgosalvez** [comment]
I'm still experiencing this on v2.1.1, both on light/dark mode.
![IMG_164EA01E76D5-1](https://user-images.githubusercontent.com/1798166/166673583-d8865b25-8229-4409-a3aa-d04fdeaad223.jpeg)
![IMG_75596FA35225-1](https://user-images.githubusercontent.com/1798166/166673592-ae4f2b9a-7cf4-44e1-a13c-9b139c6a42be.jpeg)
